[project]
name = "early_tde_classification"
version = "0.1.0"
description = "Early TDE classification project"
dependencies = [
	"pandas",
	"numpy"
	"matplotlib",
	"coniferest",
]


[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]
